Auteur : David Paulino
# Expected Goals
Ce Jupyter Notebook a pour but d'être un support pour la rédaction du Travail de Bachelor nommé "[insérer le nom]"

In [1]:
# Import des libs
import pandas as pd
import numpy as np
import json
# Plotting
import matplotlib.pyplot as plt
# Permet de plot des terrains de football
from mplsoccer import VerticalPitch
# Nécessaire à l'import des datasets
import os
import pathlib

#import warnings 

#pd.options.mode.chained_assignment = None
#warnings.filterwarnings('ignore')

# Données
La première partie de notebook vise à importer, visualiser et observer les caractéristiques de chacun des attributs du dataset. Cela va permettre de mieux comprendre le dataset dans son ensemble, d'observer d'éventuelles données manquantes et de pouvoir prédire à l'avance d'éventuels comportements.

In [ ]:
# Chargement des données
train = pd.DataFrame()
mypath = os.path.join(str(pathlib.Path().resolve().parents[0]), 'expected-goals', 'events')
# Permet de récupérer tous les fichiers dans le dossier /TB/events
onlyfiles = [f for f in os.listdir(mypath) if os.path.isfile(os.path.join(mypath, f))]
for file_name in onlyfiles:
    path_to_file = mypath + "/" + file_name
    
    with open(path_to_file) as f:
        data = json.load(f)
    train = pd.concat([train, pd.DataFrame(data)])

In [3]:
# Un train.describe n'a pas de sens car il nous donnera les informations des id 
# (qui ne sont pas des attributs intéressants pour un modèle)
#train.describe()

In [4]:
train = train[train["subEventName"] == "Shot"]

In [7]:
train[20:80]

,eventId,subEventName,tags,playerId,positions,matchId,eventName,teamId,matchPeriod,eventSec,subEventId,id
2169,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1202}, {'id'...",286553,"[{'y': 65, 'x': 79}, {'y': 0, 'x': 0}]",2500687,Shot,3776,1H,1449.254948,100,176436141
2221,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1212}, {'id'...",25923,"[{'y': 44, 'x': 94}, {'y': 0, 'x': 0}]",2500687,Shot,3776,1H,1644.963852,100,176436190
2295,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",286553,"[{'y': 58, 'x': 73}, {'y': 0, 'x': 0}]",2500687,Shot,3776,1H,1862.828583,100,176436256
2397,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1215}, {'id'...",25923,"[{'y': 67, 'x': 86}, {'y': 0, 'x': 0}]",2500687,Shot,3776,1H,2200.403186,100,176436340
2607,10,Shot,"[{'id': 101}, {'id': 401}, {'id': 201}, {'id':...",213308,"[{'y': 36, 'x': 80}, {'y': 0, 'x': 0}]",2500687,Shot,3776,2H,136.184670,100,176436550
2641,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1203}, {'id'...",260002,"[{'y': 42, 'x': 90}, {'y': 100, 'x': 100}]",2500687,Shot,3770,2H,251.511298,100,176436733
2702,10,Shot,"[{'id': 402}, {'id': 1214}, {'id': 1802}]",144867,"[{'y': 79, 'x': 72}, {'y': 0, 'x': 0}]",2500687,Shot,3776,2H,518.307804,100,176436637
2736,10,Shot,"[{'id': 1901}, {'id': 401}, {'id': 2101}, {'id...",250134,"[{'y': 66, 'x': 86}, {'y': 0, 'x': 0}]",2500687,Shot,3776,2H,616.285617,100,176436665
2807,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",99453,"[{'y': 62, 'x': 88}, {'y': 100, 'x': 100}]",2500687,Shot,3770,2H,805.041570,100,176436961
2953,10,Shot,"[{'id': 101}, {'id': 402}, {'id': 1205}, {'id'...",286553,"[{'y': 63, 'x': 93}, {'y': 0, 'x': 0}]",2500687,Shot,3776,2H,1464.996021,100,176436831
3181,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",242446,"[{'y': 37, 'x': 85}, {'y': 100, 'x': 100}]",2500687,Shot,3770,2H,2228.678835,100,176437249
3226,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1212}, {'id'...",242446,"[{'y': 46, 'x': 77}, {'y': 100, 'x': 100}]",2500687,Shot,3770,2H,2413.447157,100,176437276
3283,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",260002,"[{'y': 64, 'x': 76}, {'y': 100, 'x': 100}]",2500687,Shot,3770,2H,2631.492096,100,176437320
3302,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",250134,"[{'y': 39, 'x': 90}, {'y': 0, 'x': 0}]",2500687,Shot,3776,2H,2734.907431,100,176437093
3304,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",70959,"[{'y': 57, 'x': 85}, {'y': 0, 'x': 0}]",2500687,Shot,3776,2H,2737.267164,100,176437096
3325,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1203}, {'id'...",142755,"[{'y': 64, 'x': 92}, {'y': 0, 'x': 0}]",2500688,Shot,3766,1H,38.210256,100,176188964
3380,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1203}, {'id'...",5167,"[{'y': 42, 'x': 74}, {'y': 0, 'x': 0}]",2500688,Shot,3766,1H,202.445726,100,176189008
3497,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1216}, {'id'...",5167,"[{'y': 46, 'x': 91}, {'y': 0, 'x': 0}]",2500688,Shot,3766,1H,567.951667,100,176189378
3747,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",142755,"[{'y': 72, 'x': 88}, {'y': 0, 'x': 0}]",2500688,Shot,3766,1H,1333.844117,100,176189666
3757,10,Shot,"[{'id': 101}, {'id': 402}, {'id': 201}, {'id':...",5167,"[{'y': 36, 'x': 80}, {'y': 0, 'x': 0}]",2500688,Shot,3766,1H,1360.538512,100,176189687
3993,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1213}, {'id'...",5167,"[{'y': 49, 'x': 93}, {'y': 0, 'x': 0}]",2500688,Shot,3766,1H,2347.962930,100,176189936
4059,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1212}, {'id'...",28990,"[{'y': 35, 'x': 97}, {'y': 100, 'x': 100}]",2500688,Shot,3779,1H,2741.688664,100,176189298
4230,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1214}, {'id'...",5167,"[{'y': 51, 'x': 93}, {'y': 0, 'x': 0}]",2500688,Shot,3766,2H,546.262351,100,176190106
4244,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1216}, {'id'...",3803,"[{'y': 30, 'x': 77}, {'y': 0, 'x': 0}]",2500688,Shot,3766,2H,593.844545,100,176190112
4317,10,Shot,"[{'id': 101}, {'id': 402}, {'id': 201}, {'id':...",5167,"[{'y': 50, 'x': 85}, {'y': 0, 'x': 0}]",2500688,Shot,3766,2H,921.203818,100,176190153
4698,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1216}, {'id'...",412701,"[{'y': 71, 'x': 73}, {'y': 100, 'x': 100}]",2500688,Shot,3779,2H,2354.188960,100,176189903
4735,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",412701,"[{'y': 48, 'x': 87}, {'y': 100, 'x': 100}]",2500688,Shot,3779,2H,2481.178624,100,176189935
4744,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1201}, {'id'...",25673,"[{'y': 68, 'x': 94}, {'y': 100, 'x': 100}]",2500688,Shot,3779,2H,2493.059859,100,176189943
4756,10,Shot,"[{'id': 402}, {'id': 1212}, {'id': 1802}]",25641,"[{'y': 50, 'x': 83}, {'y': 100, 'x': 100}]",2500688,Shot,3779,2H,2542.117948,100,176189952
4802,10,Shot,"[{'id': 101}, {'id': 401}, {'id': 201}, {'id':...",28115,"[{'y': 57, 'x': 86}, {'y': 0, 'x': 0}]",2500688,Shot,3766,2H,2702.596849,100,176190417
4809,10,Shot,"[{'id': 401}, {'id': 1210}, {'id': 1802}]",29616,"[{'y': 28, 'x': 72}, {'y': 100, 'x': 100}]",2500688,Shot,3779,2H,2781.007741,100,176190005
4905,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1203}, {'id'...",256084,"[{'y': 64, 'x': 88}, {'y': 100, 'x': 100}]",2500689,Shot,3804,1H,244.534752,100,176522097
4990,10,Shot,"[{'id': 1901}, {'id': 401}, {'id': 2101}, {'id...",25770,"[{'y': 63, 'x': 87}, {'y': 0, 'x': 0}]",2500689,Shot,3771,1H,647.176407,100,176522208
5074,10,Shot,"[{'id': 1901}, {'id': 402}, {'id': 201}, {'id'...",149054,"[{'y': 29, 'x': 93}, {'y': 100, 'x': 100}]",2500689,Shot,3804,1H,987.342719,100,176522238
5090,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",26124,"[{'y': 49, 'x': 88}, {'y': 100, 'x': 100}]",2500689,Shot,3804,1H,1067.347045,100,176522264
5115,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1208}, {'id'...",209086,"[{'y': 43, 'x': 76}, {'y': 0, 'x': 0}]",2500689,Shot,3771,1H,1146.410486,100,176522378
5206,10,Shot,"[{'id': 402}, {'id': 1216}, {'id': 1802}]",26311,"[{'y': 62, 'x': 74}, {'y': 100, 'x': 100}]",2500689,Shot,3804,1H,1439.608442,100,176522382
5219,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",7915,"[{'y': 31, 'x': 90}, {'y': 0, 'x': 0}]",2500689,Shot,3771,1H,1488.792613,100,176522481
5233,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",26100,"[{'y': 58, 'x': 76}, {'y': 100, 'x': 100}]",2500689,Shot,3804,1H,1543.463254,100,176522407
5457,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",280115,"[{'y': 61, 'x': 80}, {'y': 0, 'x': 0}]",2500689,Shot,3771,1H,2384.581160,100,176522766
5516,10,Shot,"[{'id': 402}, {'id': 1216}, {'id': 1802}]",26100,"[{'y': 67, 'x': 84}, {'y': 100, 'x': 100}]",2500689,Shot,3804,1H,2579.983885,100,176522685
5606,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 201}, {'id'...",209086,"[{'y': 68, 'x': 76}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,58.447776,100,176522863
5658,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1215}, {'id'...",14722,"[{'y': 55, 'x': 71}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,204.877140,100,176522926
5687,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1202}, {'id'...",280115,"[{'y': 67, 'x': 90}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,279.795341,100,176522957
5712,10,Shot,"[{'id': 101}, {'id': 1901}, {'id': 403}, {'id'...",28123,"[{'y': 51, 'x': 93}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,325.000126,100,176522998
5715,10,Shot,"[{'id': 401}, {'id': 1215}, {'id': 1802}]",256084,"[{'y': 46, 'x': 74}, {'y': 100, 'x': 100}]",2500689,Shot,3804,2H,387.065646,100,176522946
5769,10,Shot,"[{'id': 101}, {'id': 1901}, {'id': 401}, {'id'...",25770,"[{'y': 65, 'x': 89}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,501.496671,100,176523055
5808,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1212}, {'id'...",70088,"[{'y': 54, 'x': 93}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,722.549416,100,176523111
5848,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1216}, {'id'...",26124,"[{'y': 40, 'x': 97}, {'y': 100, 'x': 100}]",2500689,Shot,3804,2H,890.088749,100,176523089
5884,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",256084,"[{'y': 44, 'x': 73}, {'y': 100, 'x': 100}]",2500689,Shot,3804,2H,1000.935722,100,176523114
6048,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",366401,"[{'y': 36, 'x': 92}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,1450.712366,100,176523397
6111,10,Shot,"[{'id': 101}, {'id': 1901}, {'id': 402}, {'id'...",28123,"[{'y': 47, 'x': 78}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,1612.049280,100,176523480
6201,10,Shot,"[{'id': 401}, {'id': 2101}, {'id': 1802}]",25770,"[{'y': 43, 'x': 76}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,2057.037301,100,176523576
6219,10,Shot,"[{'id': 403}, {'id': 201}, {'id': 1211}, {'id'...",25770,"[{'y': 56, 'x': 91}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,2098.344631,100,176523592
6291,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1216}, {'id'...",25835,"[{'y': 19, 'x': 71}, {'y': 100, 'x': 100}]",2500689,Shot,3804,2H,2383.749650,100,176523512
6367,10,Shot,"[{'id': 402}, {'id': 201}, {'id': 1221}, {'id'...",134494,"[{'y': 50, 'x': 94}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,2633.799576,100,176523691
6370,10,Shot,"[{'id': 402}, {'id': 2101}, {'id': 1802}]",25598,"[{'y': 52, 'x': 91}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,2637.056779,100,176523693
6374,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1216}, {'id'...",7915,"[{'y': 40, 'x': 75}, {'y': 0, 'x': 0}]",2500689,Shot,3771,2H,2645.296732,100,176523695
6466,10,Shot,"[{'id': 401}, {'id': 201}, {'id': 1214}, {'id'...",25474,"[{'y': 42, 'x': 87}, {'y': 100, 'x': 100}]",2500690,Shot,3785,1H,153.246076,100,176186843
6686,10,Shot,"[{'id': 101}, {'id': 403}, {'id': 201}, {'id':...",25716,"[{'y': 45, 'x': 97}, {'y': 0, 'x': 0}]",2500690,Shot,3777,1H,822.597854,100,176187113